targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - always_specify_types
            - public_member_api_docs