name: presensa_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  appwrite: ^18.0.0
  cached_network_image: ^3.4.1
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^16.0.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.6.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pretty_dio_logger: ^1.4.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.0.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  go_router_builder: ^3.0.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    # - assets/images/

flutter_gen:
  output: lib/src/constants/gen/
  integrations:
    flutter_svg: true